name: giro_jogos
description: A Flutter project for iOS, Android, and PWA with Firebase backend
publish_to: 'none'
version: 1.0.0+1

homepage: https://github.com/guitcastro/giro-jogos-flutter
repository: https://github.com/guitcastro/giro-jogos-flutter
license: AGPL-3.0

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter    
  
  # UI
  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.0
  provider: ^6.1.5+1
  firebase_auth: ^6.1.1
  go_router: ^17.0.0
  cloud_firestore: ^6.1.0
  
  # Auth
  google_sign_in: ^7.2.0
  sign_in_with_apple: ^7.0.1
  share_plus: ^12.0.1
  rxdart: ^0.28.0
  
  # Media & Markdown
  flutter_markdown: ^0.7.4+1
  image_picker: ^1.2.0
  firebase_storage: ^13.0.4
  file_picker: ^10.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.13
  fake_cloud_firestore: ^4.0.0
  firebase_auth_mocks: ^0.15.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
